language: ruby
rvm:
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: koDtGCqYDTpQ/8M09hdmC/qvXxktruQ42T3Yxo2xQowyA/WWUdpqRElnLGxeIU+cqM7iZxcQyQDSL14esS6A5IyfOQp/S97j+z0220TueWx4Tgp8PWdlgXxVfYWD10UAaTjS+EqoBmDxFkp8pYd8F8U6ID6aSmY0x6/PXTdFWas=
  gem: hibachi
  on:
    tags: true
    repo: tubbo/hibachi
addons:
  code_climate:
    repo_token:
      secure: UKeJwZLZ/ca8uCPb19S4PfqoDgYXucygJ7XRDfUM6KO6H43ie6adXqrV1CIIxM9oKK4mq3+XZPA8d5IMPE3E6Nq98NLEvukHCU1mwWJBjcLZzxGousFNbyFVWR7PN9Qotx5u8gRuYRfg4nNnYYNFbHB2KrHIFaUDbUP2Qn9MYnY
